/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author Anderson/Kaique/Matheus
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemCurso = new javax.swing.JMenuItem();
        menuItemTurma = new javax.swing.JMenuItem();
        menuItemInstrutor = new javax.swing.JMenuItem();
        menuItemAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSair = new javax.swing.JMenuItem();
        menuOper = new javax.swing.JMenu();
        menuItemAlocInstrutor = new javax.swing.JMenuItem();
        menuItemMatric = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho POO");

        menuCadastro.setText("Cadastros");

        menuItemCurso.setText("Curso");
        menuItemCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCursoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCurso);

        menuItemTurma.setText("Turma");
        menuItemTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTurmaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemTurma);

        menuItemInstrutor.setText("Instrutor");
        menuItemInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInstrutorActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemInstrutor);

        menuItemAluno.setText("Aluno");
        menuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlunoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemAluno);
        menuCadastro.add(jSeparator1);

        menuItemSair.setText("Sair");
        menuCadastro.add(menuItemSair);

        jMenuBar1.add(menuCadastro);

        menuOper.setText("Operações");

        menuItemAlocInstrutor.setText("Alocar Instrutor");
        menuOper.add(menuItemAlocInstrutor);

        menuItemMatric.setText("Efetuar Matrícula");
        menuOper.add(menuItemMatric);

        jMenuBar1.add(menuOper);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInstrutorActionPerformed
        new GuiInstrutor().setVisible(true);
    }//GEN-LAST:event_menuItemInstrutorActionPerformed

    private void menuItemCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCursoActionPerformed
        new GuiCurso().setVisible(true);
    }//GEN-LAST:event_menuItemCursoActionPerformed

    private void menuItemTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTurmaActionPerformed
        new GuiTurma().setVisible(true);
    }//GEN-LAST:event_menuItemTurmaActionPerformed

    private void menuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlunoActionPerformed
        new GuiAluno().setVisible(true);
    }//GEN-LAST:event_menuItemAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemAlocInstrutor;
    private javax.swing.JMenuItem menuItemAluno;
    private javax.swing.JMenuItem menuItemCurso;
    private javax.swing.JMenuItem menuItemInstrutor;
    private javax.swing.JMenuItem menuItemMatric;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemTurma;
    private javax.swing.JMenu menuOper;
    // End of variables declaration//GEN-END:variables
}
